# Generated by Django 4.1.7 on 2023-03-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="starrating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="items",
            name="description",
            field=models.CharField(max_length=100),
        ),
    ]
